apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hrcp-pvc
spec:
  volumeName: pgdata 
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
